// ===== TRANSLATIONS =====
// lang wird hier initialisiert damit t() sofort funktioniert,
// auch bevor app.js geladen wurde. app.js setzt lang nach load().
var lang = 'de';

const T = {
  de: {
    farbe:'Farbe', grand:'Grand', null:'Null', durch:'Durch.', ramsch:'Ramsch',
    karo:'Karo', herz:'Herz', pik:'Pik', kreuz:'Kreuz',
    faktor:'Faktor', punkte:'Pkt.', festWert:'Fester Wert', verlierer:'Verlierer',
    details:'Details & Modifikatoren',
    buben:'Buben', mit:'mit', ohne:'ohne', bube:'B',  // B = Bube
    koenig:'K', dame:'D',
    zusaetze:'Zusätze (+1 Faktor je)',
    hand:'Hand', schneider:'Schneider', schneiderA:'Schneider anges.',
    schwarz:'Schwarz', schwarzA:'Schwarz anges.', ouvert:'Ouvert',
    ramschExtras:'Ramsch-Extras (×2 je)',
    jungfrau:'Jungfrau', geschoben:'Geschoben',
    verdoppelungen:'Verdoppelungen (×2 je)',
    kontra:'Kontra', re:'Re', bock:'Bock',
    wertKorrektur:'Wert-Korrektur',
    verlorenX2:'Verloren ×2', verlorenHint:'(Vorzeichen wird automatisch gesetzt)',
    eintragen:'Eintragen',
    vormerken:'Vormerken',
    spielerAuswaehlen:'Spieler auswählen · Spieltyp · Eintragen',
    detailsEintragen:'Details eingeben · Eintragen',
    bekommtPunkte:'bekommt die Punkte',
    oeffnen:'Tippen zum Öffnen ↑',
    wert:'Wert', spiel:'Spiel',
    emptyText:'Noch keine Spiele.\nSpielernamen durch Tippen auf Überschrift ändern.',
    modalTitle:'Neu starten?',
    modalText:'Alle Spielstände werden gelöscht. Spielernamen bleiben erhalten.',
    abbrechen:'Abbrechen', loeschen:'Löschen',
    eingetragen:'Eintrag gelöscht', rueckgaengig:'Rückgängig',
    farbenNamen:['Karo','Herz','Pik','Kreuz'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durchmarsch',
    vierterSpieler:'4. Spieler hinzufügen',
    vierterSpielerLoeschen:'4. Spieler entfernen',
    aussetzt:'setzt aus', gibt:'gibt',
    leer:'Leer', leerHint:'Keine Punkte – Runde ohne Spieler',
    leer:'Leer', leerHint:'Keine Punkte – Runde wird notiert ohne Spieler',
    tabStd:'Σ Standard', tabSf:'SF Turnier', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Speichern', editieren:'Runde bearbeiten', abbrechenEdit:'Abbrechen', weiter:'Weiter ›',
    tisch:'Tisch', tischIntro:'Tisch eröffnen, damit Mitspieler auf ihrem eigenen Gerät live mitlesen können.',
    tischEroeffnen:'Tisch eröffnen', tischBeitreten:'Beitreten', tischCodePlatzhalter:'CODE',
    tischNichtGefunden:'Tisch nicht gefunden oder bereits geschlossen.',
    tischDuBistAnschreiber:'Du bist Anschreiber', tischDuLiestMit:'Du liest mit (nur Ansicht)',
    tischSchliessen:'Tisch schließen', tischVerlassen:'Tisch verlassen', tischFertig:'Fertig',
    tischGeschlossenHinweis:'Der Tisch wurde vom Anschreiber beendet.',
    tischFehlerErstellen:'Tisch konnte nicht erstellt werden. Bitte später erneut versuchen.',
    hinweis:'Hinweis', ok:'OK', ansichtSchliessen:'Schließen',
  },
  en: {
    farbe:'Suit', grand:'Grand', null:'Null', durch:'March', ramsch:'Ramsch',
    karo:'Diamonds', herz:'Hearts', pik:'Spades', kreuz:'Clubs',
    faktor:'Factor', punkte:'pts', festWert:'Fixed value', verlierer:'Loser',
    details:'Details & Modifiers',
    buben:'Jacks', mit:'with', ohne:'without', bube:'J',
    koenig:'K', dame:'Q',
    zusaetze:'Extras (+1 factor each)',
    hand:'Hand', schneider:'Schneider', schneiderA:'Schneider declared',
    schwarz:'Schwarz', schwarzA:'Schwarz declared', ouvert:'Ouvert',
    ramschExtras:'Ramsch extras (×2 each)',
    jungfrau:'Virgin', geschoben:'Pushed',
    verdoppelungen:'Doublings (×2 each)',
    kontra:'Contra', re:'Re', bock:'Bock',
    wertKorrektur:'Value correction',
    verlorenX2:'Lost ×2', verlorenHint:'(sign is set automatically)',
    eintragen:'Enter',
    vormerken:'Reserve',
    spielerAuswaehlen:'Select player · Game type · Enter',
    detailsEintragen:'Enter details · Enter',
    bekommtPunkte:'gets the points',
    oeffnen:'Tap to open ↑',
    wert:'Value', spiel:'Game',
    emptyText:'No rounds yet.\nTap column headers to edit player names.',
    modalTitle:'Start over?',
    modalText:'All scores will be deleted. Player names are kept.',
    abbrechen:'Cancel', loeschen:'Delete',
    eingetragen:'Entry deleted', rueckgaengig:'Undo',
    farbenNamen:['Diamonds','Hearts','Spades','Clubs'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'March',
    vierterSpieler:'Add 4th player',
    vierterSpielerLoeschen:'Remove 4th player',
    aussetzt:'sits out', gibt:'deals',
    leer:'Empty', leerHint:'No points – round without player',
    leer:'Empty', leerHint:'No points – round noted without player',
    tabStd:'Σ Standard', tabSf:'SF Tournament', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze declared',
    speichern:'Save', editieren:'Edit round', abbrechenEdit:'Cancel', weiter:'Next ›',
    tisch:'Table', tischIntro:'Open a table so other players can follow along live on their own device.',
    tischEroeffnen:'Open table', tischBeitreten:'Join', tischCodePlatzhalter:'CODE',
    tischNichtGefunden:'Table not found or already closed.',
    tischDuBistAnschreiber:'You are the scorekeeper', tischDuLiestMit:'You are viewing (read-only)',
    tischSchliessen:'Close table', tischVerlassen:'Leave table', tischFertig:'Done',
    tischGeschlossenHinweis:'The table was closed by the scorekeeper.',
    tischFehlerErstellen:'Could not create the table. Please try again later.',
    hinweis:'Note', ok:'OK', ansichtSchliessen:'Close',
  },
  fr: {
    farbe:'Couleur', grand:'Grand', null:'Null', durch:'Marche', ramsch:'Ramsch',
    karo:'Carreau', herz:'Cœur', pik:'Pique', kreuz:'Trèfle',
    faktor:'Facteur', punkte:'pts', festWert:'Valeur fixe', verlierer:'Perdant',
    details:'Détails & Modificateurs',
    buben:'Valets', mit:'avec', ohne:'sans', bube:'V',
    koenig:'R', dame:'D',
    zusaetze:'Bonus (+1 facteur chacun)',
    hand:'Main', schneider:'Schneider', schneiderA:'Schneider annoncé',
    schwarz:'Schwarz', schwarzA:'Schwarz annoncé', ouvert:'Ouvert',
    ramschExtras:'Extras Ramsch (×2 chacun)',
    jungfrau:'Vierge', geschoben:'Repoussé',
    verdoppelungen:'Doublements (×2 chacun)',
    kontra:'Contre', re:'Surcontre', bock:'Bock',
    wertKorrektur:'Correction valeur',
    verlorenX2:'Perdu ×2', verlorenHint:'(signe mis automatiquement)',
    eintragen:'Enregistrer',
    vormerken:'Réserver',
    spielerAuswaehlen:'Choisir joueur · Type · Enregistrer',
    detailsEintragen:'Saisir détails · Enregistrer',
    bekommtPunkte:'reçoit les points',
    oeffnen:'Toucher pour ouvrir ↑',
    wert:'Valeur', spiel:'Jeu',
    emptyText:'Aucune manche.\nTouchez les en-têtes pour modifier les noms.',
    modalTitle:'Recommencer ?',
    modalText:'Tous les scores seront supprimés. Les noms sont conservés.',
    abbrechen:'Annuler', loeschen:'Supprimer',
    eingetragen:'Entrée supprimée', rueckgaengig:'Annuler',
    farbenNamen:['Carreau','Cœur','Pique','Trèfle'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Ajouter 4e joueur',
    vierterSpielerLoeschen:'Retirer 4e joueur',
    aussetzt:'passe', gibt:'donne',
    leer:'Vide', leerHint:'Sans points – tour sans joueur',
    tabStd:'Σ Standard', tabSf:'SF Tournoi', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Enregistrer', editieren:'Modifier la manche', abbrechenEdit:'Annuler', weiter:'Suivant ›',
    tisch:'Table', tischIntro:'Ouvrez une table pour que les autres joueurs puissent suivre en direct sur leur propre appareil.',
    tischEroeffnen:'Ouvrir la table', tischBeitreten:'Rejoindre', tischCodePlatzhalter:'CODE',
    tischNichtGefunden:'Table introuvable ou déjà fermée.',
    tischDuBistAnschreiber:'Vous êtes le marqueur', tischDuLiestMit:'Vous suivez la partie (lecture seule)',
    tischSchliessen:'Fermer la table', tischVerlassen:'Quitter la table', tischFertig:'Terminé',
    tischGeschlossenHinweis:'La table a été fermée par le marqueur.',
    tischFehlerErstellen:'Impossible de créer la table. Réessayez plus tard.',
    hinweis:'Info', ok:'OK', ansichtSchliessen:'Fermer',
  },
  es: {
    farbe:'Palo', grand:'Grand', null:'Null', durch:'Marcha', ramsch:'Ramsch',
    karo:'Diamante', herz:'Corazón', pik:'Pica', kreuz:'Trébol',
    faktor:'Factor', punkte:'pts', festWert:'Valor fijo', verlierer:'Perdedor',
    details:'Detalles y Modificadores',
    buben:'Sotas', mit:'con', ohne:'sin', bube:'S',
    koenig:'R', dame:'D',
    zusaetze:'Extras (+1 factor c/u)',
    hand:'Mano', schneider:'Schneider', schneiderA:'Schneider declarado',
    schwarz:'Schwarz', schwarzA:'Schwarz declarado', ouvert:'Ouvert',
    ramschExtras:'Extras Ramsch (×2 c/u)',
    jungfrau:'Virgen', geschoben:'Empujado',
    verdoppelungen:'Dobles (×2 c/u)',
    kontra:'Contra', re:'Redoble', bock:'Bock',
    wertKorrektur:'Corrección valor',
    verlorenX2:'Perdido ×2', verlorenHint:'(signo se pone automáticamente)',
    eintragen:'Anotar',
    vormerken:'Reservar',
    spielerAuswaehlen:'Elegir jugador · Tipo · Anotar',
    detailsEintragen:'Introducir detalles · Anotar',
    bekommtPunkte:'obtiene los puntos',
    oeffnen:'Toca para abrir ↑',
    wert:'Valor', spiel:'Juego',
    emptyText:'Sin rondas aún.\nToca los encabezados para editar nombres.',
    modalTitle:'¿Empezar de nuevo?',
    modalText:'Todas las puntuaciones se borrarán. Los nombres se conservan.',
    abbrechen:'Cancelar', loeschen:'Borrar',
    eingetragen:'Entrada borrada', rueckgaengig:'Deshacer',
    farbenNamen:['Diamantes','Corazones','Picas','Tréboles'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Añadir 4º jugador',
    vierterSpielerLoeschen:'Quitar 4º jugador',
    aussetzt:'descansa', gibt:'reparte',
    leer:'Vacío', leerHint:'Sin puntos – ronda sin jugador',
    tabStd:'Σ Estándar', tabSf:'SF Torneo', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Guardar', editieren:'Editar ronda', abbrechenEdit:'Cancelar', weiter:'Siguiente ›',
    tisch:'Mesa', tischIntro:'Abre una mesa para que otros jugadores puedan seguir la partida en vivo desde su propio dispositivo.',
    tischEroeffnen:'Abrir mesa', tischBeitreten:'Unirse', tischCodePlatzhalter:'CÓDIGO',
    tischNichtGefunden:'Mesa no encontrada o ya cerrada.',
    tischDuBistAnschreiber:'Eres el anotador', tischDuLiestMit:'Estás viendo (solo lectura)',
    tischSchliessen:'Cerrar mesa', tischVerlassen:'Salir de la mesa', tischFertig:'Listo',
    tischGeschlossenHinweis:'La mesa fue cerrada por el anotador.',
    tischFehlerErstellen:'No se pudo crear la mesa. Inténtalo de nuevo más tarde.',
    hinweis:'Aviso', ok:'OK', ansichtSchliessen:'Cerrar',
  },
  it: {
    farbe:'Seme', grand:'Grand', null:'Null', durch:'Marcia', ramsch:'Ramsch',
    karo:'Quadri', herz:'Cuori', pik:'Picche', kreuz:'Fiori',
    faktor:'Fattore', punkte:'pt', festWert:'Valore fisso', verlierer:'Perdente',
    details:'Dettagli e Modificatori',
    buben:'Fanti', mit:'con', ohne:'senza', bube:'F',
    koenig:'R', dame:'D',
    zusaetze:'Extra (+1 fattore ciascuno)',
    hand:'Mano', schneider:'Schneider', schneiderA:'Schneider dichiarato',
    schwarz:'Schwarz', schwarzA:'Schwarz dichiarato', ouvert:'Ouvert',
    ramschExtras:'Extra Ramsch (×2 ciascuno)',
    jungfrau:'Vergine', geschoben:'Spinto',
    verdoppelungen:'Raddoppi (×2 ciascuno)',
    kontra:'Contro', re:'Raddoppio', bock:'Bock',
    wertKorrektur:'Correzione valore',
    verlorenX2:'Perso ×2', verlorenHint:'(segno impostato automaticamente)',
    eintragen:'Registra',
    vormerken:'Prenota',
    spielerAuswaehlen:'Scegli giocatore · Tipo · Registra',
    detailsEintragen:'Inserisci dettagli · Registra',
    bekommtPunkte:'ottiene i punti',
    oeffnen:'Tocca per aprire ↑',
    wert:'Valore', spiel:'Gioco',
    emptyText:'Nessuna manche.\nTocca le intestazioni per modificare i nomi.',
    modalTitle:'Ricominciare?',
    modalText:'Tutti i punteggi verranno cancellati. I nomi vengono mantenuti.',
    abbrechen:'Annulla', loeschen:'Elimina',
    eingetragen:'Voce eliminata', rueckgaengig:'Annulla',
    farbenNamen:['Quadri','Cuori','Picche','Fiori'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Aggiungi 4° giocatore',
    vierterSpielerLoeschen:'Rimuovi 4° giocatore',
    aussetzt:'passa', gibt:'distribuisce',
    leer:'Vuoto', leerHint:'Senza punti – turno senza giocatore',
    tabStd:'Σ Standard', tabSf:'SF Torneo', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Salva', editieren:'Modifica mano', abbrechenEdit:'Annulla', weiter:'Avanti ›',
    tisch:'Tavolo', tischIntro:'Apri un tavolo per far seguire la partita in diretta agli altri giocatori sul proprio dispositivo.',
    tischEroeffnen:'Apri tavolo', tischBeitreten:'Unisciti', tischCodePlatzhalter:'CODICE',
    tischNichtGefunden:'Tavolo non trovato o già chiuso.',
    tischDuBistAnschreiber:'Sei il segnapunti', tischDuLiestMit:'Stai seguendo (sola lettura)',
    tischSchliessen:'Chiudi tavolo', tischVerlassen:'Lascia il tavolo', tischFertig:'Fatto',
    tischGeschlossenHinweis:'Il tavolo è stato chiuso dal segnapunti.',
    tischFehlerErstellen:'Impossibile creare il tavolo. Riprova più tardi.',
    hinweis:'Nota', ok:'OK', ansichtSchliessen:'Chiudi',
  },
  da: {
    farbe:'Farve', grand:'Grand', null:'Null', durch:'March', ramsch:'Ramsch',
    karo:'Ruder', herz:'Hjerter', pik:'Spar', kreuz:'Klør',
    faktor:'Faktor', punkte:'pt', festWert:'Fast værdi', verlierer:'Taber',
    details:'Detaljer & Modifikatorer',
    buben:'Knægte', mit:'med', ohne:'uden', bube:'K',
    koenig:'K', dame:'D',
    zusaetze:'Tillæg (+1 faktor hver)',
    hand:'Hånd', schneider:'Schneider', schneiderA:'Schneider meldt',
    schwarz:'Schwarz', schwarzA:'Schwarz meldt', ouvert:'Ouvert',
    ramschExtras:'Ramsch-ekstra (×2 hver)',
    jungfrau:'Jomfru', geschoben:'Skubbet',
    verdoppelungen:'Fordobling (×2 hver)',
    kontra:'Kontra', re:'Re', bock:'Bock',
    wertKorrektur:'Værdikorrektur',
    verlorenX2:'Tabt ×2', verlorenHint:'(fortegn sættes automatisk)',
    eintragen:'Registrer',
    vormerken:'Reserver',
    spielerAuswaehlen:'Vælg spiller · Spilletype · Registrer',
     detailsEintragen:'Indtast detaljer · Registrer',
    bekommtPunkte:'får point',
    oeffnen:'Tryk for at åbne ↑',
    wert:'Værdi', spiel:'Spil',
    emptyText:'Ingen runder endnu.\nTryk på kolonneoverskrifter for at redigere navne.',
    modalTitle:'Start forfra?',
    modalText:'Alle scores slettes. Spillernavne bevares.',
    abbrechen:'Annuller', loeschen:'Slet',
    eingetragen:'Post slettet', rueckgaengig:'Fortryd',
    farbenNamen:['Ruder','Hjerter','Spar','Klør'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Tilføj 4. spiller',
    vierterSpielerLoeschen:'Fjern 4. spiller',
    aussetzt:'sidder over', gibt:'giver',
    leer:'Tom', leerHint:'Ingen point – runde uden spiller',
    tabStd:'Σ Standard', tabSf:'SF Turnering', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Gem', editieren:'Rediger runde', abbrechenEdit:'Annuller', weiter:'Næste ›',
    tisch:'Bord', tischIntro:'Åbn et bord, så andre spillere kan følge med live på deres egen enhed.',
    tischEroeffnen:'Åbn bord', tischBeitreten:'Deltag', tischCodePlatzhalter:'KODE',
    tischNichtGefunden:'Bord ikke fundet eller allerede lukket.',
    tischDuBistAnschreiber:'Du er skriveren', tischDuLiestMit:'Du følger med (kun visning)',
    tischSchliessen:'Luk bord', tischVerlassen:'Forlad bord', tischFertig:'Færdig',
    tischGeschlossenHinweis:'Bordet blev lukket af skriveren.',
    tischFehlerErstellen:'Bordet kunne ikke oprettes. Prøv igen senere.',
    hinweis:'Bemærk', ok:'OK', ansichtSchliessen:'Luk',
  },
  th: {
    farbe:'ไพ่สี', grand:'แกรนด์', null:'นัล', durch:'ตีตลอด', ramsch:'แรมช์',
    karo:'โพแดง', herz:'ใจ', pik:'โพดำ', kreuz:'ดอกจิก',
    faktor:'ตัวคูณ', punkte:'แต้ม', festWert:'ค่าคงที่', verlierer:'ผู้แพ้',
    details:'รายละเอียดและตัวปรับ',
    buben:'แจ็ค', mit:'มี', ohne:'ไม่มี', bube:'J',
    koenig:'K', dame:'D',
    zusaetze:'โบนัส (+1 ตัวคูณต่อใบ)',
    hand:'มือ', schneider:'ชไนเดอร์', schneiderA:'ชไนเดอร์ประกาศ',
    schwarz:'ชวาร์ซ', schwarzA:'ชวาร์ซประกาศ', ouvert:'เปิดไพ่',
    ramschExtras:'โบนัสแรมช์ (×2 ต่อรายการ)',
    jungfrau:'บริสุทธิ์', geschoben:'เลื่อน',
    verdoppelungen:'คูณสอง (×2 ต่อรายการ)',
    kontra:'คอนทรา', re:'รี', bock:'บ็อค',
    wertKorrektur:'แก้ไขค่า',
    verlorenX2:'แพ้ ×2', verlorenHint:'(เครื่องหมายถูกตั้งอัตโนมัติ)',
    eintragen:'บันทึก',
    vormerken:'จอง',
    spielerAuswaehlen:'เลือกผู้เล่น · ประเภทเกม · บันทึก',
     detailsEintragen:'กรอกรายละเอียด · บันทึก',
    bekommtPunkte:'ได้รับแต้ม',
    oeffnen:'แตะเพื่อเปิด ↑',
    wert:'ค่า', spiel:'เกม',
    emptyText:'ยังไม่มีรอบ\nแตะหัวคอลัมน์เพื่อแก้ไขชื่อผู้เล่น',
    modalTitle:'เริ่มใหม่?',
    modalText:'คะแนนทั้งหมดจะถูกลบ ชื่อผู้เล่นจะถูกเก็บไว้',
    abbrechen:'ยกเลิก', loeschen:'ลบ',
    eingetragen:'ลบรายการแล้ว', rueckgaengig:'เลิกทำ',
    farbenNamen:['โพแดง','ใจ','โพดำ','ดอกจิก'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'เพิ่มผู้เล่นที่ 4',
    vierterSpielerLoeschen:'ลบผู้เล่นที่ 4',
    aussetzt:'พัก', gibt:'แจกไพ่',
    leer:'ว่าง', leerHint:'ไม่มีคะแนน – รอบที่ไม่มีผู้เล่น',
    tabStd:'Σ มาตรฐาน', tabSf:'SF ทัวร์นาเมนต์', tabBl:'BL เบียร์แลคส์',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'บันทึก', editieren:'แก้ไขรอบ', abbrechenEdit:'ยกเลิก', weiter:'ถัดไป ›',
    tisch:'โต๊ะ', tischIntro:'เปิดโต๊ะเพื่อให้ผู้เล่นคนอื่นดูคะแนนสดบนอุปกรณ์ของตัวเอง',
    tischEroeffnen:'เปิดโต๊ะ', tischBeitreten:'เข้าร่วม', tischCodePlatzhalter:'รหัส',
    tischNichtGefunden:'ไม่พบโต๊ะ หรือปิดไปแล้ว',
    tischDuBistAnschreiber:'คุณเป็นผู้จดคะแนน', tischDuLiestMit:'คุณกำลังดูอยู่ (อ่านอย่างเดียว)',
    tischSchliessen:'ปิดโต๊ะ', tischVerlassen:'ออกจากโต๊ะ', tischFertig:'เสร็จสิ้น',
    tischGeschlossenHinweis:'โต๊ะถูกปิดโดยผู้จดคะแนนแล้ว',
    tischFehlerErstellen:'ไม่สามารถสร้างโต๊ะได้ กรุณาลองใหม่ภายหลัง',
    hinweis:'หมายเหตุ', ok:'ตกลง', ansichtSchliessen:'ปิด',
  },
  vi: {
    farbe:'Bài màu', grand:'Grand', null:'Null', durch:'Diễu hành', ramsch:'Ramsch',
    karo:'Rô', herz:'Cơ', pik:'Pích', kreuz:'Nhép',
    faktor:'Hệ số', punkte:'đ', festWert:'Giá trị cố định', verlierer:'Người thua',
    details:'Chi tiết & Điều chỉnh',
    buben:'Bồi', mit:'có', ohne:'không có', bube:'B',
    koenig:'K', dame:'D',
    zusaetze:'Thêm (+1 hệ số mỗi cái)',
    hand:'Tay', schneider:'Schneider', schneiderA:'Schneider đã tuyên bố',
    schwarz:'Schwarz', schwarzA:'Schwarz đã tuyên bố', ouvert:'Lật bài',
    ramschExtras:'Thêm Ramsch (×2 mỗi cái)',
    jungfrau:'Trinh nữ', geschoben:'Đẩy',
    verdoppelungen:'Nhân đôi (×2 mỗi cái)',
    kontra:'Contra', re:'Re', bock:'Bock',
    wertKorrektur:'Sửa giá trị',
    verlorenX2:'Thua ×2', verlorenHint:'(dấu được đặt tự động)',
    eintragen:'Ghi lại',
    vormerken:'Ghi tạm',
    spielerAuswaehlen:'Chọn người chơi · Loại game · Ghi lại',
     detailsEintragen:'Nhập chi tiết · Ghi',
    bekommtPunkte:'nhận điểm',
    oeffnen:'Chạm để mở ↑',
    wert:'Giá trị', spiel:'Trò chơi',
    emptyText:'Chưa có ván nào.\nChạm vào tiêu đề cột để sửa tên người chơi.',
    modalTitle:'Bắt đầu lại?',
    modalText:'Tất cả điểm số sẽ bị xóa. Tên người chơi được giữ lại.',
    abbrechen:'Hủy', loeschen:'Xóa',
    eingetragen:'Đã xóa mục', rueckgaengig:'Hoàn tác',
    farbenNamen:['Rô','Cơ','Pích','Nhép'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Thêm người chơi thứ 4',
    vierterSpielerLoeschen:'Xóa người chơi thứ 4',
    aussetzt:'nghỉ', gibt:'chia bài',
    leer:'Trống', leerHint:'Không có điểm – vòng không có người chơi',
    tabStd:'Σ Chuẩn', tabSf:'SF Giải đấu', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Lưu', editieren:'Sửa ván', abbrechenEdit:'Hủy', weiter:'Tiếp ›',
    tisch:'Bàn', tischIntro:'Mở một bàn để người chơi khác có thể theo dõi trực tiếp trên thiết bị của họ.',
    tischEroeffnen:'Mở bàn', tischBeitreten:'Tham gia', tischCodePlatzhalter:'MÃ',
    tischNichtGefunden:'Không tìm thấy bàn hoặc đã đóng.',
    tischDuBistAnschreiber:'Bạn là người ghi điểm', tischDuLiestMit:'Bạn đang xem (chỉ đọc)',
    tischSchliessen:'Đóng bàn', tischVerlassen:'Rời bàn', tischFertig:'Xong',
    tischGeschlossenHinweis:'Bàn đã được người ghi điểm đóng lại.',
    tischFehlerErstellen:'Không thể tạo bàn. Vui lòng thử lại sau.',
    hinweis:'Lưu ý', ok:'OK', ansichtSchliessen:'Đóng',
  },
  ja: {
    farbe:'スート', grand:'グランド', null:'ヌル', durch:'行進', ramsch:'ラムシュ',
    karo:'ダイヤ', herz:'ハート', pik:'スペード', kreuz:'クラブ',
    faktor:'係数', punkte:'点', festWert:'固定値', verlierer:'敗者',
    details:'詳細・修正',
    buben:'ジャック', mit:'あり', ohne:'なし', bube:'J',
    koenig:'K', dame:'D',
    zusaetze:'追加 (各+1係数)',
    hand:'ハンド', schneider:'シュナイダー', schneiderA:'シュナイダー宣言',
    schwarz:'シュヴァルツ', schwarzA:'シュヴァルツ宣言', ouvert:'オープン',
    ramschExtras:'ラムシュ追加 (各×2)',
    jungfrau:'ジュングフラウ', geschoben:'先送り',
    verdoppelungen:'倍増 (各×2)',
    kontra:'コントラ', re:'レ', bock:'ボック',
    wertKorrektur:'値の修正',
    verlorenX2:'負け ×2', verlorenHint:'(符号は自動設定)',
    eintragen:'記録',
    vormerken:'仮登録',
    spielerAuswaehlen:'プレイヤー選択 · ゲーム種別 · 記録',
    detailsEintragen:'詳細入力 · 記録',
    bekommtPunkte:'が点数を獲得',
    oeffnen:'タップして開く ↑',
    wert:'値', spiel:'ゲーム',
    emptyText:'まだゲームがありません。\nヘッダーをタップしてプレイヤー名を変更。',
    modalTitle:'リセットしますか？',
    modalText:'すべてのスコアが削除されます。プレイヤー名は保持されます。',
    abbrechen:'キャンセル', loeschen:'削除',
    eingetragen:'エントリを削除しました', rueckgaengig:'元に戻す',
    farbenNamen:['ダイヤ','ハート','スペード','クラブ'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'4人目のプレイヤーを追加',
    vierterSpielerLoeschen:'4人目のプレイヤーを削除',
    aussetzt:'休み', gibt:'配る',
    leer:'空', leerHint:'点数なし – プレイヤーなしのラウンド',
    tabStd:'Σ 標準', tabSf:'SF トーナメント', tabBl:'BL ビールラックス',
    spitze:'シュピッツェ', spitzeA:'シュピッツェ宣言',
    speichern:'保存', editieren:'ラウンド編集', abbrechenEdit:'キャンセル', weiter:'次へ ›',
    tisch:'テーブル', tischIntro:'テーブルを開くと、他のプレイヤーが自分の端末でスコアをリアルタイムに見られます。',
    tischEroeffnen:'テーブルを開く', tischBeitreten:'参加する', tischCodePlatzhalter:'コード',
    tischNichtGefunden:'テーブルが見つからないか、既に閉じられています。',
    tischDuBistAnschreiber:'あなたが記録係です', tischDuLiestMit:'閲覧中です(読み取り専用)',
    tischSchliessen:'テーブルを閉じる', tischVerlassen:'テーブルを離れる', tischFertig:'完了',
    tischGeschlossenHinweis:'テーブルは記録係によって閉じられました。',
    tischFehlerErstellen:'テーブルを作成できませんでした。後でもう一度お試しください。',
    hinweis:'お知らせ', ok:'OK', ansichtSchliessen:'閉じる',
  },
};

// ===== LANGUAGE =====
function t(key){ return (T[lang]&&T[lang][key]) || T['de'][key] || key; }

function toggleLangDropdown(e){
  e.stopPropagation();
  document.getElementById('langDropdown').classList.toggle('open');
}
function pickLang(l,e){
  if(e) e.stopPropagation();
  document.getElementById('langDropdown').classList.remove('open');
  setLang(l);
}