// ===== TRANSLATIONS =====
const T = {
  de: {
    farbe:'Farbe', grand:'Grand', null:'Null', durch:'Durch.', ramsch:'Ramsch',
    karo:'Karo', herz:'Herz', pik:'Pik', kreuz:'Kreuz',
    faktor:'Faktor', punkte:'Pkt.', festWert:'Fester Wert', verlierer:'Verlierer',
    details:'Details & Modifikatoren',
    buben:'Buben', mit:'mit', ohne:'ohne', bube:'B',  // B = Bube
    koenig:'K', dame:'D',
    zusaetze:'Zusätze (+1 Faktor je)',
    hand:'Hand', schneider:'Schneider', schneiderA:'Schneider anges.',
    schwarz:'Schwarz', schwarzA:'Schwarz anges.', ouvert:'Ouvert',
    ramschExtras:'Ramsch-Extras (×2 je)',
    jungfrau:'Jungfrau', geschoben:'Geschoben',
    verdoppelungen:'Verdoppelungen (×2 je)',
    kontra:'Kontra', re:'Re', bock:'Bock',
    wertKorrektur:'Wert-Korrektur',
    verlorenX2:'Verloren ×2', verlorenHint:'(Vorzeichen wird automatisch gesetzt)',
    eintragen:'Eintragen',
    vormerken:'Vormerken',
    spielerAuswaehlen:'Spieler auswählen · Spieltyp · Eintragen',
    detailsEintragen:'Details eingeben · Eintragen',
    bekommtPunkte:'bekommt die Punkte',
    oeffnen:'Tippen zum Öffnen ↑',
    wert:'Wert', spiel:'Spiel',
    emptyText:'Noch keine Spiele.\nSpielernamen durch Tippen auf Überschrift ändern.',
    modalTitle:'Neu starten?',
    modalText:'Alle Spielstände werden gelöscht. Spielernamen bleiben erhalten.',
    abbrechen:'Abbrechen', loeschen:'Löschen',
    eingetragen:'Eintrag gelöscht', rueckgaengig:'Rückgängig',
    farbenNamen:['Karo','Herz','Pik','Kreuz'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durchmarsch',
    vierterSpieler:'4. Spieler hinzufügen',
    vierterSpielerLoeschen:'4. Spieler entfernen',
    aussetzt:'setzt aus',
    leer:'Leer', leerHint:'Keine Punkte – Runde ohne Spieler',
    leer:'Leer', leerHint:'Keine Punkte – Runde wird notiert ohne Spieler',
    tabStd:'Σ Standard', tabSf:'SF Turnier', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Speichern', editieren:'Runde bearbeiten', abbrechenEdit:'Abbrechen', weiter:'Weiter ›',
  },
  en: {
    farbe:'Suit', grand:'Grand', null:'Null', durch:'March', ramsch:'Ramsch',
    karo:'Diamonds', herz:'Hearts', pik:'Spades', kreuz:'Clubs',
    faktor:'Factor', punkte:'pts', festWert:'Fixed value', verlierer:'Loser',
    details:'Details & Modifiers',
    buben:'Jacks', mit:'with', ohne:'without', bube:'J',
    koenig:'K', dame:'Q',
    zusaetze:'Extras (+1 factor each)',
    hand:'Hand', schneider:'Schneider', schneiderA:'Schneider declared',
    schwarz:'Schwarz', schwarzA:'Schwarz declared', ouvert:'Ouvert',
    ramschExtras:'Ramsch extras (×2 each)',
    jungfrau:'Virgin', geschoben:'Pushed',
    verdoppelungen:'Doublings (×2 each)',
    kontra:'Contra', re:'Re', bock:'Bock',
    wertKorrektur:'Value correction',
    verlorenX2:'Lost ×2', verlorenHint:'(sign is set automatically)',
    eintragen:'Enter',
    vormerken:'Reserve',
    spielerAuswaehlen:'Select player · Game type · Enter',
    detailsEintragen:'Enter details · Enter',
    bekommtPunkte:'gets the points',
    oeffnen:'Tap to open ↑',
    wert:'Value', spiel:'Game',
    emptyText:'No rounds yet.\nTap column headers to edit player names.',
    modalTitle:'Start over?',
    modalText:'All scores will be deleted. Player names are kept.',
    abbrechen:'Cancel', loeschen:'Delete',
    eingetragen:'Entry deleted', rueckgaengig:'Undo',
    farbenNamen:['Diamonds','Hearts','Spades','Clubs'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'March',
    vierterSpieler:'Add 4th player',
    vierterSpielerLoeschen:'Remove 4th player',
    aussetzt:'sits out',
    leer:'Empty', leerHint:'No points – round without player',
    leer:'Empty', leerHint:'No points – round noted without player',
    tabStd:'Σ Standard', tabSf:'SF Tournament', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze declared',
    speichern:'Save', editieren:'Edit round', abbrechenEdit:'Cancel', weiter:'Next ›',
  },
  fr: {
    farbe:'Couleur', grand:'Grand', null:'Null', durch:'Marche', ramsch:'Ramsch',
    karo:'Carreau', herz:'Cœur', pik:'Pique', kreuz:'Trèfle',
    faktor:'Facteur', punkte:'pts', festWert:'Valeur fixe', verlierer:'Perdant',
    details:'Détails & Modificateurs',
    buben:'Valets', mit:'avec', ohne:'sans', bube:'V',
    koenig:'R', dame:'D',
    zusaetze:'Bonus (+1 facteur chacun)',
    hand:'Main', schneider:'Schneider', schneiderA:'Schneider annoncé',
    schwarz:'Schwarz', schwarzA:'Schwarz annoncé', ouvert:'Ouvert',
    ramschExtras:'Extras Ramsch (×2 chacun)',
    jungfrau:'Vierge', geschoben:'Repoussé',
    verdoppelungen:'Doublements (×2 chacun)',
    kontra:'Contre', re:'Surcontre', bock:'Bock',
    wertKorrektur:'Correction valeur',
    verlorenX2:'Perdu ×2', verlorenHint:'(signe mis automatiquement)',
    eintragen:'Enregistrer',
    vormerken:'Réserver',
    spielerAuswaehlen:'Choisir joueur · Type · Enregistrer',
    detailsEintragen:'Saisir détails · Enregistrer',
    bekommtPunkte:'reçoit les points',
    oeffnen:'Toucher pour ouvrir ↑',
    wert:'Valeur', spiel:'Jeu',
    emptyText:'Aucune manche.\nTouchez les en-têtes pour modifier les noms.',
    modalTitle:'Recommencer ?',
    modalText:'Tous les scores seront supprimés. Les noms sont conservés.',
    abbrechen:'Annuler', loeschen:'Supprimer',
    eingetragen:'Entrée supprimée', rueckgaengig:'Annuler',
    farbenNamen:['Carreau','Cœur','Pique','Trèfle'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Ajouter 4e joueur',
    vierterSpielerLoeschen:'Retirer 4e joueur',
    aussetzt:'passe',
    leer:'Vide', leerHint:'Sans points – tour sans joueur',
    tabStd:'Σ Standard', tabSf:'SF Tournoi', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Speichern', editieren:'Bearbeiten', abbrechenEdit:'Abbrechen', weiter:'Weiter ›',
  },
  es: {
    farbe:'Palo', grand:'Grand', null:'Null', durch:'Marcha', ramsch:'Ramsch',
    karo:'Diamante', herz:'Corazón', pik:'Pica', kreuz:'Trébol',
    faktor:'Factor', punkte:'pts', festWert:'Valor fijo', verlierer:'Perdedor',
    details:'Detalles y Modificadores',
    buben:'Sotas', mit:'con', ohne:'sin', bube:'S',
    koenig:'R', dame:'D',
    zusaetze:'Extras (+1 factor c/u)',
    hand:'Mano', schneider:'Schneider', schneiderA:'Schneider declarado',
    schwarz:'Schwarz', schwarzA:'Schwarz declarado', ouvert:'Ouvert',
    ramschExtras:'Extras Ramsch (×2 c/u)',
    jungfrau:'Virgen', geschoben:'Empujado',
    verdoppelungen:'Dobles (×2 c/u)',
    kontra:'Contra', re:'Redoble', bock:'Bock',
    wertKorrektur:'Corrección valor',
    verlorenX2:'Perdido ×2', verlorenHint:'(signo se pone automáticamente)',
    eintragen:'Anotar',
    vormerken:'Reservar',
    spielerAuswaehlen:'Elegir jugador · Tipo · Anotar',
    detailsEintragen:'Introducir detalles · Anotar',
    bekommtPunkte:'obtiene los puntos',
    oeffnen:'Toca para abrir ↑',
    wert:'Valor', spiel:'Juego',
    emptyText:'Sin rondas aún.\nToca los encabezados para editar nombres.',
    modalTitle:'¿Empezar de nuevo?',
    modalText:'Todas las puntuaciones se borrarán. Los nombres se conservan.',
    abbrechen:'Cancelar', loeschen:'Borrar',
    eingetragen:'Entrada borrada', rueckgaengig:'Deshacer',
    farbenNamen:['Diamantes','Corazones','Picas','Tréboles'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Añadir 4º jugador',
    vierterSpielerLoeschen:'Quitar 4º jugador',
    aussetzt:'descansa',
    leer:'Vacío', leerHint:'Sin puntos – ronda sin jugador',
    tabStd:'Σ Estándar', tabSf:'SF Torneo', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Speichern', editieren:'Bearbeiten', abbrechenEdit:'Abbrechen', weiter:'Weiter ›',
  },
  it: {
    farbe:'Seme', grand:'Grand', null:'Null', durch:'Marcia', ramsch:'Ramsch',
    karo:'Quadri', herz:'Cuori', pik:'Picche', kreuz:'Fiori',
    faktor:'Fattore', punkte:'pt', festWert:'Valore fisso', verlierer:'Perdente',
    details:'Dettagli e Modificatori',
    buben:'Fanti', mit:'con', ohne:'senza', bube:'F',
    koenig:'R', dame:'D',
    zusaetze:'Extra (+1 fattore ciascuno)',
    hand:'Mano', schneider:'Schneider', schneiderA:'Schneider dichiarato',
    schwarz:'Schwarz', schwarzA:'Schwarz dichiarato', ouvert:'Ouvert',
    ramschExtras:'Extra Ramsch (×2 ciascuno)',
    jungfrau:'Vergine', geschoben:'Spinto',
    verdoppelungen:'Raddoppi (×2 ciascuno)',
    kontra:'Contro', re:'Raddoppio', bock:'Bock',
    wertKorrektur:'Correzione valore',
    verlorenX2:'Perso ×2', verlorenHint:'(segno impostato automaticamente)',
    eintragen:'Registra',
    vormerken:'Prenota',
    spielerAuswaehlen:'Scegli giocatore · Tipo · Registra',
    detailsEintragen:'Inserisci dettagli · Registra',
    bekommtPunkte:'ottiene i punti',
    oeffnen:'Tocca per aprire ↑',
    wert:'Valore', spiel:'Gioco',
    emptyText:'Nessuna manche.\nTocca le intestazioni per modificare i nomi.',
    modalTitle:'Ricominciare?',
    modalText:'Tutti i punteggi verranno cancellati. I nomi vengono mantenuti.',
    abbrechen:'Annulla', loeschen:'Elimina',
    eingetragen:'Voce eliminata', rueckgaengig:'Annulla',
    farbenNamen:['Quadri','Cuori','Picche','Fiori'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Aggiungi 4° giocatore',
    vierterSpielerLoeschen:'Rimuovi 4° giocatore',
    aussetzt:'passa',
    leer:'Vuoto', leerHint:'Senza punti – turno senza giocatore',
    tabStd:'Σ Standard', tabSf:'SF Torneo', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Speichern', editieren:'Bearbeiten', abbrechenEdit:'Abbrechen', weiter:'Weiter ›',
  },
  da: {
    farbe:'Farve', grand:'Grand', null:'Null', durch:'March', ramsch:'Ramsch',
    karo:'Ruder', herz:'Hjerter', pik:'Spar', kreuz:'Klør',
    faktor:'Faktor', punkte:'pt', festWert:'Fast værdi', verlierer:'Taber',
    details:'Detaljer & Modifikatorer',
    buben:'Knægte', mit:'med', ohne:'uden', bube:'K',
    koenig:'K', dame:'D',
    zusaetze:'Tillæg (+1 faktor hver)',
    hand:'Hånd', schneider:'Schneider', schneiderA:'Schneider meldt',
    schwarz:'Schwarz', schwarzA:'Schwarz meldt', ouvert:'Ouvert',
    ramschExtras:'Ramsch-ekstra (×2 hver)',
    jungfrau:'Jomfru', geschoben:'Skubbet',
    verdoppelungen:'Fordobling (×2 hver)',
    kontra:'Kontra', re:'Re', bock:'Bock',
    wertKorrektur:'Værdikorrektur',
    verlorenX2:'Tabt ×2', verlorenHint:'(fortegn sættes automatisk)',
    eintragen:'Registrer',
    vormerken:'Reserver',
    spielerAuswaehlen:'Vælg spiller · Spilletype · Registrer',
     detailsEintragen:'Indtast detaljer · Registrer',
    bekommtPunkte:'får point',
    oeffnen:'Tryk for at åbne ↑',
    wert:'Værdi', spiel:'Spil',
    emptyText:'Ingen runder endnu.\nTryk på kolonneoverskrifter for at redigere navne.',
    modalTitle:'Start forfra?',
    modalText:'Alle scores slettes. Spillernavne bevares.',
    abbrechen:'Annuller', loeschen:'Slet',
    eingetragen:'Post slettet', rueckgaengig:'Fortryd',
    farbenNamen:['Ruder','Hjerter','Spar','Klør'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Tilføj 4. spiller',
    vierterSpielerLoeschen:'Fjern 4. spiller',
    aussetzt:'sidder over',
    leer:'Tom', leerHint:'Ingen point – runde uden spiller',
    tabStd:'Σ Standard', tabSf:'SF Turnering', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Speichern', editieren:'Bearbeiten', abbrechenEdit:'Abbrechen', weiter:'Weiter ›',
  },
  th: {
    farbe:'ไพ่สี', grand:'แกรนด์', null:'นัล', durch:'ตีตลอด', ramsch:'แรมช์',
    karo:'โพแดง', herz:'ใจ', pik:'โพดำ', kreuz:'ดอกจิก',
    faktor:'ตัวคูณ', punkte:'แต้ม', festWert:'ค่าคงที่', verlierer:'ผู้แพ้',
    details:'รายละเอียดและตัวปรับ',
    buben:'แจ็ค', mit:'มี', ohne:'ไม่มี', bube:'J',
    koenig:'K', dame:'D',
    zusaetze:'โบนัส (+1 ตัวคูณต่อใบ)',
    hand:'มือ', schneider:'ชไนเดอร์', schneiderA:'ชไนเดอร์ประกาศ',
    schwarz:'ชวาร์ซ', schwarzA:'ชวาร์ซประกาศ', ouvert:'เปิดไพ่',
    ramschExtras:'โบนัสแรมช์ (×2 ต่อรายการ)',
    jungfrau:'บริสุทธิ์', geschoben:'เลื่อน',
    verdoppelungen:'คูณสอง (×2 ต่อรายการ)',
    kontra:'คอนทรา', re:'รี', bock:'บ็อค',
    wertKorrektur:'แก้ไขค่า',
    verlorenX2:'แพ้ ×2', verlorenHint:'(เครื่องหมายถูกตั้งอัตโนมัติ)',
    eintragen:'บันทึก',
    vormerken:'จอง',
    spielerAuswaehlen:'เลือกผู้เล่น · ประเภทเกม · บันทึก',
     detailsEintragen:'กรอกรายละเอียด · บันทึก',
    bekommtPunkte:'ได้รับแต้ม',
    oeffnen:'แตะเพื่อเปิด ↑',
    wert:'ค่า', spiel:'เกม',
    emptyText:'ยังไม่มีรอบ\nแตะหัวคอลัมน์เพื่อแก้ไขชื่อผู้เล่น',
    modalTitle:'เริ่มใหม่?',
    modalText:'คะแนนทั้งหมดจะถูกลบ ชื่อผู้เล่นจะถูกเก็บไว้',
    abbrechen:'ยกเลิก', loeschen:'ลบ',
    eingetragen:'ลบรายการแล้ว', rueckgaengig:'เลิกทำ',
    farbenNamen:['โพแดง','ใจ','โพดำ','ดอกจิก'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'เพิ่มผู้เล่นที่ 4',
    vierterSpielerLoeschen:'ลบผู้เล่นที่ 4',
    aussetzt:'พัก',
    leer:'ว่าง', leerHint:'ไม่มีคะแนน – รอบที่ไม่มีผู้เล่น',
    tabStd:'Σ มาตรฐาน', tabSf:'SF ทัวร์นาเมนต์', tabBl:'BL เบียร์แลคส์',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Speichern', editieren:'Bearbeiten', abbrechenEdit:'Abbrechen', weiter:'Weiter ›',
  },
  vi: {
    farbe:'Bài màu', grand:'Grand', null:'Null', durch:'Diễu hành', ramsch:'Ramsch',
    karo:'Rô', herz:'Cơ', pik:'Pích', kreuz:'Nhép',
    faktor:'Hệ số', punkte:'đ', festWert:'Giá trị cố định', verlierer:'Người thua',
    details:'Chi tiết & Điều chỉnh',
    buben:'Bồi', mit:'có', ohne:'không có', bube:'B',
    koenig:'K', dame:'D',
    zusaetze:'Thêm (+1 hệ số mỗi cái)',
    hand:'Tay', schneider:'Schneider', schneiderA:'Schneider đã tuyên bố',
    schwarz:'Schwarz', schwarzA:'Schwarz đã tuyên bố', ouvert:'Lật bài',
    ramschExtras:'Thêm Ramsch (×2 mỗi cái)',
    jungfrau:'Trinh nữ', geschoben:'Đẩy',
    verdoppelungen:'Nhân đôi (×2 mỗi cái)',
    kontra:'Contra', re:'Re', bock:'Bock',
    wertKorrektur:'Sửa giá trị',
    verlorenX2:'Thua ×2', verlorenHint:'(dấu được đặt tự động)',
    eintragen:'Ghi lại',
    vormerken:'Ghi tạm',
    spielerAuswaehlen:'Chọn người chơi · Loại game · Ghi lại',
     detailsEintragen:'Nhập chi tiết · Ghi',
    bekommtPunkte:'nhận điểm',
    oeffnen:'Chạm để mở ↑',
    wert:'Giá trị', spiel:'Trò chơi',
    emptyText:'Chưa có ván nào.\nChạm vào tiêu đề cột để sửa tên người chơi.',
    modalTitle:'Bắt đầu lại?',
    modalText:'Tất cả điểm số sẽ bị xóa. Tên người chơi được giữ lại.',
    abbrechen:'Hủy', loeschen:'Xóa',
    eingetragen:'Đã xóa mục', rueckgaengig:'Hoàn tác',
    farbenNamen:['Rô','Cơ','Pích','Nhép'],
    sf:'SF',
    rgh:'RGH', ramschGHhint:'',
    ramschDurchHint:'Durch',
    vierterSpieler:'Thêm người chơi thứ 4',
    vierterSpielerLoeschen:'Xóa người chơi thứ 4',
    aussetzt:'nghỉ',
    leer:'Trống', leerHint:'Không có điểm – vòng không có người chơi',
    tabStd:'Σ Chuẩn', tabSf:'SF Giải đấu', tabBl:'BL Bierlachs',
    spitze:'Spitze', spitzeA:'Spitze anges.',
    speichern:'Speichern', editieren:'Bearbeiten', abbrechenEdit:'Abbrechen', weiter:'Weiter ›',
  },
};

// ===== LANGUAGE =====
function t(key){ return (T[lang]&&T[lang][key]) || T['de'][key] || key; }

function toggleLangDropdown(e){
  e.stopPropagation();
  document.getElementById('langDropdown').classList.toggle('open');
}
function pickLang(l,e){
  if(e) e.stopPropagation();
  document.getElementById('langDropdown').classList.remove('open');
  setLang(l);
}